### ISSUE TITLE
Zeitsteuerung 

### ISSUE THREAD

**Issue by Bonze255** [i-am-offline/smarthome.plugin.autoblind#1]
Wie wird eine reine Zeitsteuerung realisiert? 
funktioniert dies mit as_value_time = 20:00 ?

**Comment by i-am-offline** [comment]
Grundsätzlich kann mit den "time"-Bedingungen eine reine Zeitsteuerung realisiert werden. 
Die Bedingung

    as_value_time = 20:00 

ist jedoch nur erfüllt, wenn die Prüfung der Bedingungen exakt um 20:00 Uhr durchgeführt wird (nicht um 19:59 und nicht um 20:01).

Für Zeitbedingungen sind daher min- und max-Bedingungen besser geeignet. Für einen Zustand, der zwischen 20:00 und 22:00 Uhr aktiv sein soll schreibst du

    as_min_time = 20:00
    as_max_time = 22:00

Bitte beachte, dass min immer kleiner als max sein muss. Für Zeiträume, die über Mitternacht hinweggehen, musst du min und max tauschen und das ganze dann negieren (umkehren). Also beispielsweise

    as_min_time = 06:00
    as_max_time = 20:00
    as_negate_time = True

Damit definierst du einen Zeitraum von 20:00 Uhr bis 06:00 Uhr
    

P.S: Fragen besser im KNX-User-Forum ([http://knx-user-forum.de/forum/supportforen/smarthome-py](http://knx-user-forum.de/forum/supportforen/smarthome-py)) stellen, da schauen mehr Leute rein ..
