### ISSUE TITLE
Enable ordering of actions

### ISSUE THREAD

**Issue by i-am-offline** [i-am-offline/smarthome.plugin.autoblind#10]
Actions are not necessarily executed in the order of their definition. It should be possible to define the order in which the actions should be executed. For this a new attribute `as_order_<actionname>` will be introduced which can be set to a numeric value. The value defines the order to execute the actions.

**Comment by onkelandy** [comment]
Is there no way to automatically assign an order number while reading the item? I guess adding an additional attribute might clutter the autoblind definitions quite a bit.
Maybe you could assign the order number by adding a ", ordernumber" after the as_set_value = item?

**Comment by i-am-offline** [comment]
I thought of this, too, but I have discarded this way for two reasons. When I add several "parameters" for one action into on argument, I need to split it the argument at some "magic" characters (in your example the comma). What if the value to be used contains this "magic" character, too? The second reason is, that it makes it harder to understand the action after some time. Who would know which value at which position has which meaning after not working with the plugin for some time?

Also I don't think, that it will clutter the config files very much. As for most actions the order does not matter, this attribute is planned as optional attribute. So for most actions there is no need to add these attributes. However, for some actions it might be very important (e.g. the suspend- and the suspend-name item in your case)

After shNG 1.3 has been released it might be useful to add a new action type which takes a list of (key: value) pairs as argument containing all options for one action. Using a yaml configuration file this should be easy readable. However in the current conf format I think entering such a parameter could be to complex and error-prone.

**Comment by onkelandy** [comment]
I would nevertheless go for the comma option because meanwhile there are already quite many extra attributes for attributes ;)
In my opinion the comma is perfect as it is used as a delimiter in plugin configs, etc. As you are not allowed to use it in item names I don't think that there will be any problem? Or what do you have in mind?

You could then put all the following specials directly to the item: repeat, delay, force, order. Like
as_set_item = value:10, order:1, repeat:yes,, force:yes, delay: 10

**Comment by i-am-offline** [comment]
The problem with this format is, that "value" could be a string, containing a comma. This would break the parsing.
But it's close to what I mentioned for yaml configuration files using a list format.

    as_action_<somename>:
        - function: set
        - value: 10
        - order: 1
        - repeat: yes
        [...]

**Comment by i-am-offline** [comment]
I have thought about having an attribute containing all relevant information for the action in list format again. I think it does not matter to implement it now, because the conf files support a list format, too. I will create a new issue for this.

**Comment by i-am-offline** [comment]
Action order can now be set via attribute `as_order_<name>`. This attribute takes any numerical value. Actions are sorted ascending by this value upon execution to determine the execution order.

Combined attribute as_action_\<name\> (#13) also has now a parameter `order: <num>`

**Comment by i-am-offline** [comment]
Documentation has been added, closing this issue.
