### ISSUE TITLE
Prepare Version 1.2.2

### ISSUE THREAD

**Issue by i-am-offline** [i-am-offline/smarthome.plugin.autoblind#14]
New branch for finalizing version 1.2.2 has been created. 
Final tests in progress.

**Comment by onkelandy** [comment]
The recent develop branch is the same as this one, right? Just updated and testing...

**Comment by i-am-offline** [comment]
Currently the only difference is, that in this branch the version is already set to 1.2.2. However, this branch will get only bugfixes until the version can be released while the develop branch is open for further developments ...

**Comment by i-am-offline** [comment]
Version 1.2.2 will be the base for upcoming version 1.4.0
