### ISSUE TITLE
Error when "set to" value of as_action can not be determined

### ISSUE THREAD

**Issue by onkelandy** [i-am-offline/smarthome.plugin.autoblind#15]
Wird in einem Zustand ein Item gesetzt, das nicht existiert, wird dieser Aufruf normalerweise einfach ignoriert. Soll der zu setzende Wert aber aus einem anderen Item ausgelesen werden, das nicht existiert, wird der komplette Zustand ignoriert (determined item does not exist). Super wäre, wenn das Evaluieren des zu setzenden Wertes nur dann stattfindet oder "kontrolliert" wird, wenn das zu verändernde Item auch tatsächlich existiert.

Beispiel:
Gewisse Items sollen alle auf die gleichen default Zustände zurückgreifen. Bei manchen Items werden allerdings andere Dinge geschaltet, also zB dimmbare Leuchte vs normale Schalt-Leuchte. Der zu setzende Wert wird wiederum durch ein Item ermittelt - und hier beginnt das Problem:
```                      
                [<zustandsname>]
                    [[on_enter_or_stay]]
                    as_action_schalten = function: set | to: item:..settings.sollwert.<Zustandsname>
                    as_action_dimmen_warm = function: set | to: item:..settings.sollwert.<Zustandsname>
                    as_action_dimmen_kalt = function: set | to: item:..settings.sollwert.<Zustandsname>
```     

Wenn jetzt also Leuchte X alle oben angegebenen Settings-Items definiert hat, ist alles bestens. 
Wenn Leuchte Y aber kein dimmen-Item - und somit auch kein settings.sollwert hat, gibt es die Meldung:
Ignoring state.. determined item XYZ does not exist

Was natürlich auch stimmt. Wenn ich aber zB as_action_dimmen_kalt = function: set | to: 0 eingebe, wird diese Aktion einfach ignoriert, wenn das zu ändernde Item nicht existiert. So sollt es sein ;) Aktuell könnte es nur dadurch gelöst werden, dass alle Items die gleichen settings.XYZ bekommen, unabhängig davon, ob sie Sinn machen oder nicht. Das macht die Sache aber unnötig kompliziert und unübersichtlich finde ich.

**Comment by onkelandy** [comment]
Ich hab jetzt bei mir die Dummy-Items erstellt und die Sache läuft.. Dennoch denke ich, dass es einigen helfen würde, wenn dieser "Fehler" irgendwie anders abgefangen werden könnte @i-am-offline

**Comment by i-am-offline** [comment]
Für Actions werden nun Probleme bei der Initialisierung als Warnung geloggt und nicht mehr als Fehler weitergegeben. Dadurch wird nur die betroffene Action ignoriert (Commit 69b049d). Bitte mal schauen, ob dass das ist, was Du dir vorstellst.

**Comment by onkelandy** [comment]
Hab mal meine Dummy-Items deaktiviert und deinen Commit getestet. Sieht sehr gut aus.. macht so auf jeden Fall Sinn und erleichtert bestimmt die Konfiguration bei einigen.

P.S.: Cool, dass sich hier wieder was tut ;)
