### ISSUE TITLE
Make plugin compatible with smarthomeNG 1.4

### ISSUE THREAD

**Issue by onkelandy** [i-am-offline/smarthome.plugin.autoblind#18]
* create plugin.yaml
* use self.get_parameter_value to approve attributes
* Fix CLI Commands problem: Plugin version 1.4 expects a "group" of cli commands. Right now I get the error: missing 1 required positional argument: 'usage'
* add plugin to official plugin repo ;)

**Comment by gamade** [comment]
+1
manual suspend function does not work in current shng develop branch.

**Comment by i-am-offline** [comment]
I'll have a look at the issues, however it may take until February before I have time to do so.

**Comment by gamade** [comment]
FYI: 
I changed some lines in AutoBlindCliCommands.py to get the cli commands registered:

Include:
`from lib.plugin import Plugins`

new Syntax for add_command (needs bugfix in cli plugin as well):
```
                cli.add_command("as_list", self.cli_list, "autoblind", "as_list: list AutoState items")
                cli.add_command("as_detail", self.cli_detail, "autoblind", "as_detail [asItem]: show details on AutoState item [asItem]")

```


```
    def _get_cli_plugin(self):
        # noinspection PyBroadException
        plugins = Plugins.get_instance()
        try:
            for plugin in plugins.return_plugins():
                if plugin._shortname == 'cli':
                    self.logger.debug("cli plugin found.")
                    return plugin
        except Exception:
            self.logger.info("cli plugin NOT found.")
            return None


```

**Comment by gamade** [comment]
Bugfix für plugins/cli/init.py

```
def add_command(self, command, function, **group**, usage):
    """
    Add command to list of available commands
    :param command: Command to add
    :param function: Function to execute for command
    :param usage: Usage string for help-command
    """
    self.commands.add_command(command, function, **group**, usage)
```

**Comment by onkelandy** [comment]
Thanks for the update. Autoblind is running without any error now but I can't use the CLI commands.. Says "unknown command"?

**Comment by i-am-offline** [comment]
A new branch "Version 1.4.0" is available which contains the adaptions. All adaptions are made based on the rc_v1.4.2-branch of SmarthomeNG

**Comment by onkelandy** [comment]
Looks very good, thanks alot!! Any chance that you look into the other issues and/or ideas soon?

**Comment by gamade** [comment]
Had an error:

`2018-02-03  09:25:41 WARNING  EG.entrance.window.shutter.auto.manuell Item EG.entrance.window.shutter.auto.manuell: problem evaluating sh.autoblind_plugin_functions.manual_item_update_eval('EG.entrance.window.shutter.auto.manuell', caller, source): 'SmartHome' object has no attribute 'autoblind_plugin_functions'`

With removing an indent in __init__.py line 61:         `self.get_sh().autoblind_plugin_functions = AutoBlindFunctions.AbFunctions(self.get_sh())`
fixed that error.

**Comment by i-am-offline** [comment]
For the 1.4-branch, i have removed several functions, which have been marked as obsolete in the past
- manual lock/suspend
- method AbEval.get_item
- leave conditions
