### ISSUE TITLE
Rules not evaluating with new SmarthomeNG 1.5 master

### ISSUE THREAD

**Issue by onkelandy** [i-am-offline/smarthome.plugin.autoblind#24]
Looks like the rules evaluation doesn't get triggered anymore by a sole "eval_trigger".
Adding a "eval: true" in the rules section fixes the problem, nevertheless an automatic retriggering without the eval attribute would be fine. Thanks!

**Comment by thernst-de** [comment]
PR for smarthomeNG Plugins Repository has been provided.

**Comment by onkelandy** [comment]
Thumbs up! Are you back in business? ;)
