### ISSUE TITLE
Doku und "[]"

### ISSUE THREAD

**Issue by gamade** [i-am-offline/smarthome.plugin.autoblind#3]
Hallo,

in der Doku https://github.com/i-am-offline/smarthome.plugin.autoblind/wiki/Doku-DE sind bei den Zuständen teilweise ein Klammernpaar [] zu wenig, z.B. haben "[[[[rules]]]]" und "[[[[Tag]]]]" die gleiche Klammer-Hierarchie.

**Comment by i-am-offline** [comment]
Danke für den Hinweis, sollte nun behoben sein.
