### ISSUE TITLE
Zustandswechsel per (Auto-)Timer

### ISSUE THREAD

**Issue by gamade** [i-am-offline/smarthome.plugin.autoblind#4]
Hallo,

ich habe folgendes Problem:
- Es soll ein Zustandswechsel erfolgen, wenn eine gewisse Zeit verstrichen ist. 
- Die Zeit soll über ein Item änderbar sein
- Die Zeit kann nur wenige Sekunden betragen. 

Der Lösungsansatz die Cycle Time zu Reduzieren, erhöht die Last da jedes Mal die komplette Zustandsermittlung läuft.

Die Lösung einen zusätzliches autotimer-item per eval_trigger mit aufzunehmen und den timer beim Zustandswechsel zu aktivieren, reduziert aufgrund einer Ereignis basierenden Zustandsermittlung die Last, aber die Zeit ist nicht frei über ein Item einstellbar.   

Ein Workaround wäre eine separate Logik - ist aber nicht gerade im Sinn einer durchgängigen und verständlichen Software. 

Vielleicht ist es sinnvoll, einen einstellbaren, zeitgesteuerten Zustandswechsel in das autoblind Plugin mit aufzunehmen? Oder würde es mehr Sinn machen, sh.py bezüglich der autotimer = x = y Funktion zu flexibilisieren?

**Comment by i-am-offline** [comment]
Mit 'as_delay_<Aktion>' kannst du eine Aktion verzögert ausführen. Du könntest auf einen Trigger per Cycle komplett verzichten und über so eine verzögerte Aktion dein AutoBlind-Objektitem schreiben und dadurch erneut eine Zustandsermittlung auslösen. Siehe https://github.com/i-am-offline/smarthome.plugin.autoblind/wiki/Doku-DE#einstellungen-zum-ausl%C3%B6sen-der-zustandsermittlung und https://github.com/i-am-offline/smarthome.plugin.autoblind/wiki/Doku-DE#verz%C3%B6gertes-ausf%C3%BChren-einer-aktion in der Doku.

**Comment by gamade** [comment]
Danke für den Hinweis, wer lesen kann...
Für die Aktion "away" habe ich bool Item konfiguriert: 
> as_item_away = HAUS.mode.state.away

Im Zustand LEAVING führe ich dann Aktion zeitverzögert aus:
> as_delay_away = 30

Klappt soweit: Im Zustand wird 
> Action 'away: Add 30 second timer 'HAUS.mode.state.away-AbItemDelayTimer' for delayed execution.
protokolliert und nach der Zeit auch das Item auf "False" gesetzt. 
> Delay Timer 'HAUS.mode.state.away-AbItemDelayTimer': Set 'HAUS.mode.state.away' to 'False'

Gibt es nun auch die Möglichkeit das Item auf True zu setzen? Die Syntax von autotimer (as_delay_away = 30 = 1) habe ich schon ohne Erfolg probiert...

**Comment by i-am-offline** [comment]
Ja, klar. Siehe https://github.com/i-am-offline/smarthome.plugin.autoblind/wiki/Doku-DE#item-auf-einen-wert-setzen:

    as_set_away = 1

**Comment by gamade** [comment]
Ok, ich dacht das die as_set_ Operationen sofort wirken... funktioniert.

Jetzt bekomme ich folgenden Log Output:

> 2016-11-18 09:11:41.668906 Delay Timer 'HAUS.mode.state.away-AbItemDelayTimer': Set 'HAUS.mode.state.away' to 'True'

> 2016-11-18 09:11:41.669980 Update state of item FSM Haus Modus ============================================
> 2016-11-18 09:11:41.670197 Update triggered by Eval (item=HAUS.mode.fsm.rules source=HAUS.mode.state.away dest=None)
> 2016-11-18 09:11:41.670388 Eval initially triggered by AutoBlind Plugin (item=HAUS.mode.state.away source=None)
> 2016-11-18 09:11:41.670516 Ignoring changes from AutoBlind Plugin

Das Item HAUS.mode.state.away wird auf 1 gesetzt, aber die FSM wird nicht neu getriggert... 

Setze ich HAUS.mode.state.away manuell, läuft die Zustandsermittlung mittels 

> eval_trigger = HAUS.mode.state.*

**Comment by gamade** [comment]
UPDATE:
Wenn ich ein Hilfsitem nutze um state.away indirekt zu triggern, kommt letztendlich auch die Meldung "Ignoring changes from AutoBlind Plugin". Kann man das irgendwie überschreiben, sodass die Änderung scheinbar von "extern" kommt?

**Comment by gamade** [comment]
Noch was: in AutoBlindItem.py  wird unter update_state() alles ignoriert, was orginär von Autoblind getriggert wurde. Warum ist das so?

**Comment by i-am-offline** [comment]
Das verhindert, dass bei Aktionen durch das AutoBlind-Plugin, das Plugin selbst in den Suspend-Status wechseln will. Du hast aber recht, in deinem Fall ist das Kontraproduktiv. Ich schaue mir das nochmal an ... habe da schon eine Idee ...

**Comment by gamade** [comment]
Wäre super wenn Du da eine Idee hättest... ich nämlich nicht so recht weiter und ich möchte cycle = ... vermeiden und eher per events triggern was allgemein Ressourcen schonender ist...

**Comment by i-am-offline** [comment]
Ich habe einen Commit in den Develop-Zweig gepusht, der verhindern sollte, dass der Filter anspricht, wenn man das AutoBlind-Objektitem direkt ändert.

**Comment by gamade** [comment]
Danke für den Commit, den ich heute Mittag kurz getestet habe aber noch nicht zu Laufen bekommen habe:

1. Delay per as_delay_away = 30 erzeugt nach wie vor einen Trigger, der nach 30 Sekunden aktiv wird und autoblind triggert, jedoch läuft keine Auswertung:

```
2016-11-29 13:08:58.133404 Update state of item FSM Haus Modus ============================================
2016-11-29 13:08:58.133612 Update triggered by Eval (item=HAUS.mode.fsm.rules source=HAUS.mode.state.away dest=None)
2016-11-29 13:08:58.133814 Eval initially triggered by AutoBlind Plugin (item=HAUS.mode.state.away source=None)
2016-11-29 13:08:58.133958 **Ignoring changes from AutoBlind Plugin**
```

2. Im knx-user-forum gab es einen Tipp, doch direkt das FSM Item zu triggern. Habe ich mal implementiert und prüfe mit einer zweiter Einstiegs-Bedingung das Alter des leaving-Status.  Das ist m.E. auch der elegante Weg (per Event die Zustandsermittlung anzustoßen, anstatt über Items und eval_trigger zu gehen)...

Action Item per 

> as_item_fsm = HAUS.mode.fsm.rules

 definiert und im Status Leaving per 

> as_delay_fsm       = 30

aktiviert. Leider funktioniert das nicht. Es kommt weder die Log Meldung, dass ein Delay Timer aktiviert wurde, noch wird nach 30 Sekunden die Zustandsermittlung aufgerufen. 

Any Ideas?

**Comment by onkelandy** [comment]
Also bei mir scheint es wunderbar zu klappen...
			as_item_retrigger = steckdosen.autoblind.steckdosentrigger

			[[[['restart']]]]
				type = foo
				name = Shutdown
				as_set_suspend = False
				as_set_retrigger = True
				as_delay_retrigger = 10

Du meinst, dass es besser wäre, statt über den Trigger direkt auf das rules Item zu gehen?

**Comment by gamade** [comment]
Ich bin mir (noch) nicht ganz sicher, aber gefühlt ist es besser und zukünftig flexibler die Zustandsermittlung getrennt anzustoßen. 

Es gäbe dann verschiedene Events die eine Zustandsermittlung auslösen (eval_trigger, cycle, delays, etc.) aber die Zustandsermittlung selbst klärt unabhängig davon welchen Zustand sie einnimmt und welche damit verbundenen Aktionen ausgelöst werden. 

Gerade wenn ein Timer läuft kann es sein, dann ein anderer Event den Zustand zwischendurch ändert... Beispiel:
Ich ändere den Zustand von "at home" auf "leaving", welcher nach einen Timeout auf "away" wechseln soll. Im Regelfall funktioniert das auch, aber was passiert, wenn "leaving" manuell abgebrochen wird und in "at home" zurück gesetzt wird bevor der timer auslöst? Dann kommt doch doch der Timer (ausser er wird in "at home" gelöscht) und wechselt trotzdem in "away"... 

Ich glaube es wäre rein vom Design her besser, "away" aufgrund des Alters von "leaving" auszulösen. Der Timer ist nur eine Hilfskonstrukt um die Zustandsermittlung zu triggern.

Vielleicht ist ja auch ein Lösungsansatz den "cycle timer" in Abhängigkeit des aktuellen Zustands zu konfigurieren... das wäre dann so einen art erweiterter Timer - wenn einmal ein Event (warum auch immer) verschluckt würde oder ein Neustart vom System erfolgt (letzter Zustand gecached, z.B. "leaving" aber es fehlt der Timer der "away" triggert...)

**Comment by gamade** [comment]
Heute Mittag noch einmal probiert über Zusatz Trigger-Item "HAUS.mode.trigger.away" - triggert zwar nach 30s aber stoppt mit "Ignoring changes form AutoBlind plugin":

> git status
> On branch develop
> Your branch is up-to-date with 'origin/develop'.
> nothing to commit, working tree clean

Log:

> 2016-11-30 12:06:13.142313 Delay Timer 'HAUS.mode.trigger.away-AbItemDelayTimer': Set 'HAUS.mode.trigger.away' to 'True'
> 2016-11-30 12:06:13.143315 Update state of item FSM Haus Modus ============================================
> 2016-11-30 12:06:13.143526 Update triggered by Eval (item=HAUS.mode.fsm.rules source=HAUS.mode.trigger.away dest=None)
> 2016-11-30 12:06:13.143711 Eval initially triggered by AutoBlind Plugin (item=HAUS.mode.trigger.away source=None)
> 2016-11-30 12:06:13.143854 Ignoring changes from AutoBlind Plugin
>

**Comment by i-am-offline** [comment]
Du musst direkt das Item "HAUS.mode.fsm.rules" ändern, damit es funktioniert. Der Hintergrund ist, dass das Plugin Itemänderungen, die vom Plugin selbst ausgelöst werden, normalerweise ignoriert. Sonst würde jede Itemänderung ja das Plugin wieder triggern und das Plugin würde entweder in den Suspend-Modus gehen (sofern implementiert) oder in einer Endlosschleife landen.

Der letzte Commit sorgt dafür, dass ein anderer "Caller" mitgegeben wird, wenn das Plugin direkt das Objektitem schreibt (und damit die Neuermittlung des Status auslöst). 

Zur Verdeutlichung ein kleines Beispiel:

    [test]	
    	[[retrigger]]
    		[[[item]]]
    			type = bool
    			value = False
    			
    		[[[rules]]]
    			type = bool
    			name = Automatik Test Retrigger
    			as_plugin = active
    			as_item_test = test.retrigger.item
    			as_item_trigger = test.retrigger.rules
    			as_startup_delay = -1
    			
    			[[[[state1]]]]				
    				as_set_test = True
    				as_set_trigger = True
    				as_delay_trigger = 5
    				[[[[[enter]]]]]
    					as_value_test = False
    				
    			[[[[state2]]]]
    				as_set_test = False
    				[[[[[enter]]]]]
    					as_value_test = True

Wenn diese Automatik getriggert wird (z. b. über das CLI Plugin mit `up test.retrigger.rules = True`) wird zunächst der Status "state1" aktiviert, das Item test.retrigger.item wird auf True gesetzt. Nach 5 Sekunden (`as_delay_trigger = 5`)wird die Statusermittlung neu durchgeführt (`as_set_trigger = True`) und dann wird der Status "state2" aktiviert, der das Item test.retrigger.item wieder auf False setzt.

**Comment by gamade** [comment]
Jetzt funktioniert es - danke!
Ich hatte as_set_trigger = True vergessen...

**Comment by onkelandy** [comment]
Wie löse ich denn die Problematik am einfachsten, wenn der Zustand eines Items von einem anderen "Gesamtzustand" abhängt? Also angenommen, haus.anwesend soll auch über autoblind gesteuert werden. Sobald sich nun dieser Zustand ändert, sollen einige andere Items, wie zB Lichter, Steckdosen, etc. getriggert werden, um die Evaluierung neu durchzuführen.

Ist hier die einzige Lösung, im Haupzustand selbst alle Unter-Item-Autoblind.rules zu triggern? Ist irgendwie recht umständlich und unübersichtlich :(

**Comment by i-am-offline** [comment]
@onkelandy Für deinen Gesamtzustand definierst du ein "laststate_id"-Item. Dieses Item kannst du bei abhängigen Zuständen in den eval_trigger einbauen, dann wird die Zustandsermittlung der abhängigen zustände getriggert, wenn sich der Gesamtzustand ändert. Zusätzlich kannst du bei Bedarf auch die laststate_id des Gesamtzustands als Bedingung für die abhängigen Zustände verwenden ...

Wenn es nur um das Schalten von Lichtern, etc. geht, kannst du auch das Feature "[Alle Items, die ein bestimmtes Attribut haben, auf den Wert dieses Attributs setzen](https://github.com/i-am-offline/smarthome.plugin.autoblind/wiki/Doku-DE#alle-items-die-ein-bestimmtes-attribut-haben-auf-den-wert-dieses-attributs-setzen)" verwenden. Das ist bei vielen anzusteuernden Items unter Umständen einfacher, als einzelne `as_set-<Aktionsname>` Aktionen zu definieren. Allerdings macht es das ggf. etwas aufwändiger, alle Aktionen, die einem Zustand zugeordnet sind, zu erkennen.

**Comment by onkelandy** [comment]
Ah, super, danke für den Tipp. Es ist auch tatsächlich nötig die state_id als Bedingung zu verwenden, da Items, die durch das Hauptitem geschalten werden, erst schalten, nachdem die state_id gesetzt ist.

Aber so funzt das bestens!
