### ISSUE TITLE
repeat_actions specific for single actions?

### ISSUE THREAD

**Issue by onkelandy** [i-am-offline/smarthome.plugin.autoblind#6]
Is it possible to implement the repeat_actions not only for the whole rules section but for specific actions? I sometimes would like to force the retrigger of the state evaluation but not to re-trigger the actions in that specific state.

So something like a as_repeat_XYZ = true or false would be pretty awsome. So if set manually to true it ignores the global setting, whereas when set to false the action doesn't get evaluated when re-entering the state.

**Comment by i-am-offline** [comment]
Feature sollte nun funktionieren. Bitte mal aus dem Debug-Zwei ausprobieren.

Die Einstellung erfolgt im Zustands-Item über das Attribut "as_repeat_<Aktionsname>"

Sofern zu einer Aktion das Attribut "as_repeat_<Aktionsname>" angegeben ist, überschreibt dieses Attribut die Angabe aus dem Attribut "as_repeat_actions" im Objekt-Item für die betreffende Action.

**Comment by onkelandy** [comment]
Hmmm. ich wäre jetzt davon ausgegangen, dass ich bei einem Item, das keine repeat_actions Angabe hat folgender Eintrag im Suspend-Zustand
```
as_force_suspend = True
as_repeat_suspend = False
```

zum richtigen Ergebnis führen würde. Es wird aber nach wie vor der Suspsendzustand "verlängert", wenn der Zustandsautomat "von außen" neu getriggert wird (durch ein Item).
```
2017-01-07 07:05:54.375800 Staying at licht.og.kueche.automatik.rules.suspend ('Ausgesetzt')
2017-01-07 07:05:54.376577       Action 'retrigger: Removing previous delay timer 'licht.og.kueche.automatik.rules-AbItemDelayTimer'.
2017-01-07 07:05:54.381390       Action 'retrigger: Add 60 second timer 'licht.og.kueche.automatik.rules-AbItemDelayTimer' for delayed execution.  Repeat allowed by item configuration.
2017-01-07 07:05:54.382313       Action 'suspend': Set 'licht.og.kueche.automatik.suspend' to 'False' (Force)
2017-01-07 07:05:54.387295       Action 'suspend': Set 'licht.og.kueche.automatik.suspend' to 'True'. Repeat allowed by action configuration.
2017-01-07 07:05:54.388973       Action 'suspend_end: Add 1 second timer 'licht.og.kueche.automatik.autostate_suspend_end-AbItemDelayTimer' for delayed execution.  Repeat allowed by item configuration.
```

Kann es sein, dass derzeit nur ein positives repeat möglich ist?

**Comment by i-am-offline** [comment]
Wenn as_repeat_actions nicht explizit gesetzt ist, wird dort als Defaultwert "True" verwendet.  Sofern as_repeat_<Actionname> gesetzt ist, sollte das jedoch den Wert aus as_repeat_actions übersteuern egal was in as_repeat_actions gesetzt ist.
Dein Eintrag im Suspend-Zustand sollte daher vom Prinzip her das Problem lösen.

Im Log schaut es so aus, als erkennt er das "as_repeat_suspend" nicht. Es steht sowohl bei retrigger als auch bei suspend "Repeat allowed by item configuration.". Das heißt, der Repeat ist durch as_repeat_actions (bzw. dessen Defaultwert) erlaubt. 
Wenn hier der Wert aus as_repeat_<Action> greifen würde, stünde hier "Repeat [allowed|denied] by action configuration".

Bei der Initialisierung der AutoBlind Items nach dem Start von shNG schreibt das Plugin die komplette gelesene Konfiguration ins erweiterte log. Schau mal bitte nach, ob dort bei den Actions des Suspend-Zustands was von "repeat" steht.

**Comment by onkelandy** [comment]
Beim Init steht repeat:false direkt bei der Action set/force suspend

**Comment by i-am-offline** [comment]
Habe da noch einen Fehler entdeckt. Fix ist im Develop-Zweig.

**Comment by onkelandy** [comment]
Jetzt klappt es mit dem repeat False by action. Wunderbar!

Allerdings hatten wir einen soliden Denkfehler, was den Suspend-Zustand anlangt. Dadurch, dass nun das repeat aus ist, wird natürlich auch das force_suspend nicht mehr ausgeführt, wenn das Item ein weiteres Mal manuell getriggert wurde.

Das richtige Verhalten wäre ja, dass ein force ausgeführt wird, wenn das enter_manuell Set erfüllt ist, aber dass es eben nicht ausgeführt wird, wenn das enter_stay erfüllt ist. Heißt, die Repeat-Aktion müsste den Enter-Bedingungen verknüpfbar sein :(

Oder es gibt sowas wie ne vorgegebene Suspend-Funktion, auf die man im Suspend-Zustand referenziert und wo dann alles intern so geregelt wird, damit alles klappt?
Wäre dann aber wieder eher passend im https://github.com/i-am-offline/smarthome.plugin.autoblind/issues/5

**Comment by i-am-offline** [comment]
Issue ist erledigt. Suspend-Thematik wird in #5 weiter bearbeitet.

**Comment by i-am-offline** [comment]
`as_repeat_<Aktionsname>` wird nicht in die Doku aufgenommen und ggf. in Zukunft wieder entfernt. Das beabsichtigte Verhalten kann durch #11 besser abgebildet werden

**Comment by i-am-offline** [comment]
@onkelandy Nutzt du diese Funktionalität? Ich denke darüber nach, sie direkt wieder zu entfernen ....

**Comment by onkelandy** [comment]
Die Funktion ist jetzt ja auch in der anderen Schreibweise as_action_<name> implementiert, oder? Dann kannst es ruhig entfernen, werde demnächst eh auf die neue Schreibweise umstellen, wo ich es noch nicht gemacht hab.

**Comment by i-am-offline** [comment]
Auch aus as_action möchte ich den Repeat-Parameter wieder entfernen. Über die "Ereignisse" on_enter, on_stay und on_enter_or_stay kann das in meinen Augen besser abgedeckt werden.

**Comment by onkelandy** [comment]
Ich hatte irgendeinen Anwendungsfall, wo ich mir das mit dem repeat gewünscht hätte. Ich glaub es ging um den Sollwert einer Leuchte, bei dem der Mastertrigger für den BWM immer wieder auf True gesetzt werden sollte, der Rest aber nicht. 

Könnte mir generell vorstellen, dass es auch im STAY den Bedarf an sowas geben könnte. Fände ich schade, wenn das Feature wieder raus fliegt, jetzt wo es eh schon implementiert ist und funktioniert.
