### ISSUE TITLE
Mark certain functions as obsolete

### ISSUE THREAD

**Issue by i-am-offline** [i-am-offline/smarthome.plugin.autoblind#8]
Several functions are to be marked as "obsolete". These functions have been removed from the documentation since a long time. The functions can be replaced by implementing according states as described in the manual:
* hardcoded static lock item --> use lock state instead
* hardcoded static suspend item --> use suspend state instead
* maybe some more functionality

Usage of this functions should produce error messages first. After a grace period of about 6 month the functions should be removed.

**Comment by i-am-offline** [comment]
Further functionality to be markes as obsolete:

- leave conditionsets

**Comment by onkelandy** [comment]
Speaking of "leaving"..
Would love to see a feature to trigger actions on leaving a state by the way ;)
Would make things much easier i.e. for the lock and suspend states but also for other situations.

**Comment by i-am-offline** [comment]
Functions marked as obsolete have been removed in version 1.4.0
